[package]
name = "tui-scrollview"
version = "0.3.2"
authors = ["Joshka"]
description = "A simple scrollable view for Ratatui"
license = "MIT OR Apache-2.0"
repository = "https://github.com/joshka/tui-scrollview"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2.0.4"
ratatui = "0.26.1"

[dev-dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
lipsum = "0.9.0"
